GET http://localhost:3001/notes

###

POST http://localhost:3001/notes/create
Content-Type: application/json

{
    "title":"how so"
}

###

DELETE http://localhost:3001/notes/delete/637ce5fee1166910ec1dd3aa

###

PUT http://localhost:3001/notes/update/637ce5ace1166910ec1dd3a3
Content-Type: application/json

{
    "content":"new content"
}